### ISSUE TITLE
Wrong error message for creating folder with the same name

### ISSUE THREAD

**Issue by Segelzwerg** [hhu-propra2/abschlussprojekt-mopse#246] opened 2020-03-23 10:53 UTC

**Comment by realemx** [comment] 2020-03-23 10:54
![grafik](https://user-images.githubusercontent.com/49307158/77309498-10a50f80-6cfd-11ea-9508-5cc920e8da1c.png)

**Comment by Thabb** [comment] 2020-03-23 15:37
Doesn't this come from the way a http post-request is handled? If the object already exists, post becomes just an update, or am I wrong?

**Comment by iTitus** [comment] 2020-03-23 15:41
nope caused by typo in DirectoryServiceImpl: https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/master/src/main/java/mops/businesslogic/directory/DirectoryServiceImpl.java#L233-L234

**Comment by iTitus** [comment] 2020-03-24 14:09
Closed by #265

**Closed by iTitus** 2020-03-24 14:09 UTC
Labels: bug
